model = "gpt-6-astra"
model_reasoning_effort = "ultra"
personality = "pragmatic"
notify = [ "/Users/joshxfi/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended" ]
plan_mode_reasoning_effort = "high"
service_tier = "default"

[projects."/Users/joshxfi/projects/open-source/react-highlight-popover"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/work/referenta"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/startup/umamin"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/umedu-ccs"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/github-stats"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/math3ds-le"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/maths3ds-le"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/bun-local-llm"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/umedu"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/startup/frameyu"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/mkms"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/codex-stuff"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/noteside"]
trust_level = "trusted"

[projects."/Users/joshxfi/projects/open-source/ngit"]
trust_level = "trusted"

[projects."/Users/joshxfi/Documents/Codex/2026-08-01/my"]
trust_level = "trusted"

[projects."/Users/joshxfi/Documents/Codex/2026-08-01/my-storage"]
trust_level = "trusted"

[projects."/Users/joshxfi/Documents/Codex/2026-08-01/my-storage-is-full-a"]
trust_level = "trusted"

[projects."/Users/joshxfi/Documents/Codex/2026-08-06/https-ylhcwftnwlzoeqtilnfj-supabase-co-rest-v1"]
trust_level = "trusted"

[projects."/Users/joshxfi/Documents/Codex/2026-08-06/https-ylhcwftnwlzoeqtilnfj-supabase-co-rest-v1-2"]
trust_level = "trusted"

[projects."/Users/joshxfi/Documents/Codex/2026-09-03/how-x20"]
trust_level = "trusted"

[features]
hooks = true
shell_snapshot = true
goals = true
js_repl = false

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/joshxfi/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/joshxfi/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.posthog]
last_updated = "2026-09-10T15:47:41Z"
last_revision = "33c066c80776a962a4233d76b20a3317733070b4"
source_type = "git"
source = "https://github.com/PostHog/ai-plugin.git"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."codex-security@openai-curated"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 2
"gpt-5.6-sol" = 2

[desktop]
appearanceLightCodeThemeId = "codex"
usePointerCursors = false
selected-avatar-id = "custom:koi"
followUpQueueMode = "queue"
dock-icon-preference = "app-default"
conversationDetailMode = "STEPS_PROSE"

[desktop.appearanceLightChromeTheme]
accent = "#0169cc"
contrast = 45
ink = "#0d0d0d"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#751ed9"

[desktop.appearanceDarkChromeTheme]
accent = "#339cff"
contrast = 60
ink = "#ffffff"
opaqueWindows = false
surface = "#181818"

[desktop.appearanceDarkChromeTheme.fonts]
[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#40c977"
diffRemoved = "#fa423e"
skill = "#ad7bf9"

[desktop.open-in-target-preferences]
global = "terminal"

[desktop.open-in-target-preferences.perPath]
"/Users/joshxfi/projects/work/referenta" = "terminal"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/joshxfi/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/joshxfi/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.901.41123"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/joshxfi/.codex/plugins/cache/openai-bundled/browser/26.901.41123/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/joshxfi/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = [ "mcp" ]
cwd = "."
enabled = false

[shell_environment_policy.set]
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "9230e2bd8b24b7ac7a0ba6774c64bf0d78ecdabbdd91d0ed627b02a587bae2df"
